### ISSUE TITLE
Compile error with bison 3.8 - previous declaration of yyerror

### ISSUE THREAD

**Issue by heitbaum** [heimdal/heimdal#830]
**Describe the bug**
Compiling heimdal 7.7.0 (and master) with bison 3.8 errors with mismatching previous declarations of yyerror.

**To Reproduce**
Compile with bison 3.8 instead of bison 3.7.6

if the following lines are removed from the generated .c and .h files then the compile continues further.
```
+#if !defined yyerror && !defined YYERROR_IS_DECLARED
+void yyerror (const char *msg);
+#endif
+#if !defined yylex && !defined YYLEX_IS_DECLARED
+int yylex (void);
+#endif
+
```

**Desktop (please complete the following information):**
Linux 5.14.2
Gcc 10.3.0

**Additional context**

the following files are impacted:
```
lib/com_err/parse.c
lib/sl/slc-gram.c
lib/sl/slc-gram.h
```

the following diff shows the differences between bison 3.7.6 and 3.8 for the yyerror declaration.
```
diff -Nur heimdal-7.7.0a/.x86_64-linux-gnu/lib/com_err/parse.c build.LibreELEC-Generic.x86_64-11.0-devel/build/heimdal-7.7.0/.x86_64-linux-gnu/lib/com_err/parse.c
--- heimdal-7.7.0a/.x86_64-linux-gnu/lib/com_err/parse.c        2021-09-09 22:31:21.322228478 +1000
+++ build.LibreELEC-Generic.x86_64-11.0-devel/build/heimdal-7.7.0/.x86_64-linux-gnu/lib/com_err/parse.c 2021-09-09 23:00:57.819599416 +1000
@@ -1,4 +1,4 @@
-/* A Bison parser, made by GNU Bison 3.7.6.  */
+/* A Bison parser, made by GNU Bison 3.8.  */
 
 /* Bison implementation for Yacc-like parsers in C
 
@@ -46,10 +46,10 @@
    USER NAME SPACE" below.  */
 
 /* Identify Bison output, and Bison version.  */
-#define YYBISON 30706
+#define YYBISON 30800
 
 /* Bison version string.  */
-#define YYBISON_VERSION "3.7.6"
+#define YYBISON_VERSION "3.8"
 
 /* Skeleton name.  */
 #define YYSKELETON_NAME "yacc.c"
@@ -209,8 +209,16 @@
 
 extern YYSTYPE yylval;
 
+#if !defined yyerror && !defined YYERROR_IS_DECLARED
+void yyerror (const char *msg);
+#endif
+#if !defined yylex && !defined YYLEX_IS_DECLARED
+int yylex (void);
+#endif
+
 int yyparse (void);
 
+
 #endif /* !YY_YY_PARSE_H_INCLUDED  */
 /* Symbol kind.  */
 enum yysymbol_kind_t
```

**Comment by lhoward** [comment]
Does it still exist in master?

**Comment by heitbaum** [comment]
> Does it still exist in master?

Will check.

**Comment by heitbaum** [comment]
> Does it still exist in master?

Confirmed failing with be9f26e0645d6efcf02852caaea8ba000472971b

```
make[2]: Entering directory '/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/heimdal-be9f26e0645d6efcf02852caaea8ba000472971b/.x86_64-linux-gnu/lib/com_err'
  YACC     parse.c
updating parse.h
  CC       compile_et.o
  CC       parse.o
parse.c:213:6: error: conflicting types for 'yyerror'
 void yyerror (const char *msg);
      ^~~~~~~
/var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-11.0-devel/build/heimdal-be9f26e0645d6efcf02852caaea8ba000472971b/lib/com_err/parse.y:38:6: note: previous declaration of 'yyerror' was here
 void yyerror (char *s);
      ^~~~~~~
parse.c: In function 'yyparse':
```

**Comment by heitbaum** [comment]
Reference from bison mailing list: https://www.mail-archive.com/bison-patches@gnu.org/msg07739.html

**Comment by lhoward** [comment]
Changing the `yyerror()` prototype to `const char *` seems to work (as in, doesn't break with bison 2.x which I'm using).

**Comment by heitbaum** [comment]
I’ll have a look in the morning. I will let you know. Good night.
