### ISSUE TITLE
Missing undef.h

### ISSUE THREAD

**Issue by jelmer** [heimdal/heimdal#170]
Heimdal's master branch fails to build for me at the moment:

evp-openssl.c:73:19: fatal error: undef.h: No such file or directory

@nicowilliams This appears to have been introduced by 490337f4f9a81afdf180d1a56ba83b8513335dbd

**Comment by nicowilliams** [comment]
Oops.  I'll push it after brunch.

**Comment by nicowilliams** [comment]
I've pushed a fix.

Travis-CI is failing in make check, but the output is not sufficiently
useful.  I'll see about updating .travis.yml to cat test-suite.log
files.

**Comment by jelmer** [comment]
Thanks for the quick fix!

On 16 April 2016 20:18:45 BST, Nico Williams <notifications@github.com> wrote:
>I've pushed a fix.
>
>Travis-CI is failing in make check, but the output is not sufficiently
>useful.  I'll see about updating .travis.yml to cat test-suite.log
>files.
>
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/heimdal/heimdal/issues/170#issuecomment-210876686

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicowilliams** [comment]
On Sat, Apr 16, 2016 at 12:23:04PM -0700, Jelmer Vernooij wrote:
> Thanks for the quick fix!

The Windows build is also fixed now.

The Travis build completes but its make check fails.  I suspect this is
because the OpenSSL in Travis' VMs must be cut down, and a number of
Heimdal tests depend on having older algorithms (e.g., because of
PKCS#12, which hasn't had new PBEs in a long time; some static PKCS#12
files in the tree used for testing are encrypted in RC2...).

My fix for the Travis problem is to make the OpenSSL backend fallback on
the hcrypto backend, like the Windows and PKCS#11 backends do, but
unlike the OS X (Common Crypto) backend.  I do think we should have a
./configure --with-hcrypto-fallback=yes|no option to control this
behavior, but not right now.

**Comment by nicowilliams** [comment]
And Travis is now past the previous test issues and looks set to be
happy.

**Comment by nicowilliams** [comment]
Fixed with 514f719.
