### ISSUE TITLE
Errors when compiling with Visual Studio 2010 (Visual Studio 10.0)

### ISSUE THREAD

**Issue by spaetow** [heimdal/heimdal#139]
I'm attempting to compile Heimdal 1.5 on Windows 7 with VS 2010 (v10.0). I get multiple messages:

filename.c 
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\errno.h(94) : warning C4005: 'EAFNOSUPPORT' : macro redefinition
        [heimdal directory]\out\dest_i386\inc\roken.h(64) : see previous definition of 'EAFNOSUPPORT'

In the end, I also get: 

socket.c
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\errno.h(94) : warning C4005: 'EAFNOSUPPORT' : macro redefinition
        X:\PS\SSP\heimdal\out\dest_i386\inc\roken.h(64) : see previous definition of 'EAFNOSUPPORT'
.\socket.c(63) : error C2065: 'in6addr_any' : undeclared identifier
.\socket.c(63) : error C2440: '=' : cannot convert from 'int' to 'IN6_ADDR'
.\socket.c(282) : error C2065: 'IPPROTO_IPV6' : undeclared identifier

Of course, with the error, I get a failure to build... 

I use the 'Visual Studio Command Prompt' to load the environment (which sets the environment to 'Microsoft Visual Studio 2010 x86' tools). Is there anything that I'm doing wrong?

**Comment by jaltman** [comment]
I would not expect Heimdal 1.5 to compile using Visual Studio 10.0.   You should either build the 1.6 branch on Windows or the master branch.

**Comment by spaetow** [comment]
Thanks Jeffrey. When I go back to Visual Studio 2008, I still see the following errors:

socket.c
.\socket.c(63) : error C2065: 'in6addr_any' : undeclared identifier
.\socket.c(63) : error C2440: '=' : cannot convert from 'int' to 'IN6_ADDR'
.\socket.c(282) : error C2065: 'IPPROTO_IPV6' : undeclared identifier

According to the README in the Windows directory, 1.5 should build with VS 2008 (v9.0)? Unfortunately I'm stuck with v1.5 because of the project I'm tasked with.

**Comment by jaltman** [comment]
At one point 1.5 built on Windows.   It may have been broken by a later patch applied for UNIX.  I do not know.  

There are serious problems with the side by side assemblies that were fixed for 1.6 that can result in data corruption or crashes when multiple assembly versions are present on a machine.   The 1.5 series should not be used on the Windows platform.

**Comment by spaetow** [comment]
Ahh, in that case, I'll close this. :-)
